version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db-pgadmin:
    container_name: db-pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - 16543:80
  app:
    container_name: app
    depends_on:
      - db
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081